name: Dependency Health

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  dependency-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Configure Android SDK environment
        run: |
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> "$GITHUB_ENV"
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> "$GITHUB_ENV"
          echo "PATH=$PATH:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> "$GITHUB_ENV"

      - name: Accept Android SDK licenses
        run: |
          set +e
          yes | sdkmanager --licenses > /dev/null
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 141 ]; then
            exit $status
          fi

      - name: Ensure required Android packages are installed
        run: |
          set +e
          yes | sdkmanager \
            "platforms;android-36" \
            "platform-tools" \
            "build-tools;36.0.0" > /dev/null
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 141 ]; then
            exit $status
          fi

      - name: Prepare Gradle caching
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Run dependency updates report
        run: ./gradlew --no-daemon dependencyUpdates -Drevision=release

      - name: Upload dependency report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-updates
          path: build/dependencyUpdates/
          if-no-files-found: error
