name: Dependency Health

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  dependency-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Android toolchain
        uses: ./.github/actions/setup-android

      - name: Run dependency updates report
        run: ./gradlew --no-daemon dependencyUpdates -Drevision=release

      - name: Upload dependency report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-updates
          path: build/dependencyUpdates/
          if-no-files-found: error
