name: Instrumented Smoke Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  connected-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Configure Android SDK environment
        run: |
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> "$GITHUB_ENV"
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> "$GITHUB_ENV"
          echo "PATH=$PATH:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> "$GITHUB_ENV"

      - name: Accept Android SDK licenses
        run: |
          set +e
          yes | sdkmanager --licenses > /dev/null
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 141 ]; then
            exit $status
          fi

      - name: Ensure required Android packages are installed
        run: |
          set +e
          yes | sdkmanager \
            "platforms;android-36" \
            "platforms;android-34" \
            "system-images;android-34;google_apis;x86_64" \
            "platform-tools" \
            "build-tools;36.0.0" \
            "emulator" > /dev/null
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 141 ]; then
            exit $status
          fi

      - name: Prepare Gradle caching
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Run connected Android tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-window -no-audio
          script: ./gradlew --no-daemon connectedDebugAndroidTest

      - name: Upload connected test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: connected-tests-report
          path: |
            app/build/reports/androidTests/connected/
            app/build/outputs/androidTest-results/connected/
          if-no-files-found: ignore
