name: Lint Autofix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-format:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Android toolchain
        uses: ./.github/actions/setup-android

      - name: Run formatters and lint
        run: ./gradlew --no-daemon spotlessApply lint

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply lint autofixes"
          commit_author: GitHub Actions <actions@github.com>
          push_options: --force-with-lease
          file_pattern: '.'
