name: PR Quality Gate

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  checks:
    name: Verify Build and Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Configure Android SDK environment
        run: |
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> "$GITHUB_ENV"
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> "$GITHUB_ENV"
          echo "PATH=$PATH:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> "$GITHUB_ENV"

      - name: Accept Android SDK licenses
        run: |
          set +e
          yes | sdkmanager --licenses > /dev/null
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 141 ]; then
            exit $status
          fi

      - name: Ensure required Android packages are installed
        run: |
          set +e
          yes | sdkmanager \
            "platforms;android-36" \
            "platform-tools" \
            "build-tools;36.0.0" > /dev/null
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 141 ]; then
            exit $status
          fi

      - name: Prepare Gradle caching
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Run quality checks
        run: ./gradlew --no-daemon clean spotlessCheck detekt lint test

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: |
            **/build/test-results/testDebugUnitTest/*.xml
            **/build/test-results/testReleaseUnitTest/*.xml
            **/build/reports/tests/testDebugUnitTest/
            **/build/reports/tests/testReleaseUnitTest/
          if-no-files-found: ignore

      - name: Upload detekt report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: '**/build/reports/detekt/**'
          if-no-files-found: ignore

      - name: Upload Android lint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-lint-report
          path: '**/build/reports/lint-results*'
          if-no-files-found: ignore
