name: PR Quality Gate

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  checks:
    name: Verify Build and Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Android toolchain
        uses: ./.github/actions/setup-android

      - name: Run quality checks
        run: ./gradlew --no-daemon clean spotlessCheck detekt lint test

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: |
            **/build/test-results/testDebugUnitTest/*.xml
            **/build/test-results/testReleaseUnitTest/*.xml
            **/build/reports/tests/testDebugUnitTest/
            **/build/reports/tests/testReleaseUnitTest/
          if-no-files-found: ignore

      - name: Upload detekt report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: '**/build/reports/detekt/**'
          if-no-files-found: ignore

      - name: Upload Android lint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-lint-report
          path: '**/build/reports/lint-results*'
          if-no-files-found: ignore
